### ISSUE TITLE
Reference datahub.io dataset in github description

### ISSUE THREAD

**Issue by AcckiyGerman** [datasets/house-prices-global#1]
@rufuspollock commented on [Tue Jan 09 2018](https://github.com/datasets/global-house-prices/issues/4)

![image](https://user-images.githubusercontent.com/180658/34737792-0e349034-f56f-11e7-8afc-22d6fb4fcf39.png)

---

@rufuspollock commented on [Tue Jan 09 2018](https://github.com/datasets/global-house-prices/issues/4#issuecomment-356380411)

@AcckiyGerman you may also want to add this instruction to the core data curators guide so we don't miss it on other datasets and with other curators.

**Comment by AcckiyGerman** [comment]
MOVED
The datapackage has been moved (https://github.com/datasets/house-prices-global), so I'm moving this issue there as well - https://github.com/datasets/house-prices-global/issues/1   (using zenhub)

**Comment by AcckiyGerman** [comment]
This datapackage is not presented on the datahub yet.
@Mikanebu could you please upload this datapackage under 'core' user?

**Comment by AcckiyGerman** [comment]
Reference has been updated.
Updating data curators guide...

**Comment by rufuspollock** [comment]
@AcckiyGerman is this fixed? if so can you please close.

**Comment by AcckiyGerman** [comment]
FIXED
data curators guide was updated, so people will reference datahub datasets in github repos' descriptions (at least they have an instruction now)
